services:
  backend:
    build: ./api_history
    container_name: api_history
    ports:
      - "5002:5002"
    volumes:
      - ./api_history:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./projet_orange
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend