# Utiliser une image officielle Node.js
FROM node:22

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier uniquement les fichiers de dépendances en premier (pour le cache Docker)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port utilisé par ton serveur Express
EXPOSE 5000

# Démarrer l'application
CMD ["node", "server.js"]
